Repository smvbismarck/smvsite, pull requests merged in 2020-09, with the labels that each got.

#14 Blog view
  .idea/runConfigurations/server.xml
  smvsite/blog/__init__.py
  smvsite/blog/admin.py
  smvsite/blog/apps.py
  smvsite/blog/migrations/0001_initial.py
  smvsite/blog/migrations/__init__.py
  smvsite/blog/models.py
  smvsite/blog/tests.py
  smvsite/blog/urls.py
  smvsite/blog/views.py
  smvsite/smvsite/settings.py
  smvsite/smvsite/urls.py
Labels: enhancement

#16 added docker workflow #9
  .dockerignore
  Dockerfile
  requirements.txt
Labels: enhancement

#18 Added tests for the landing page #17
  smvsite/landing/tests.py
  smvsite/smvsite/settings.py
Labels: enhancement

#20 Blog test
  .idea/runConfigurations/server.xml
  .travis.yml
  Pipfile
  Pipfile.lock
  requirements.txt
  smvsite/.flake8
  smvsite/blog/migrations/0002_auto_20200920_1713.py
  smvsite/blog/tests.py
  smvsite/blog/urls.py
  smvsite/blog/views.py
  smvsite/landing/admin.py
  smvsite/landing/models.py
  smvsite/landing/urls.py
  smvsite/smvsite/settings.py
  smvsite/smvsite/urls.py
Labels: test

#21 Komitee view
  smvsite/komitee/__init__.py
  smvsite/komitee/admin.py
  smvsite/komitee/apps.py
  smvsite/komitee/migrations/0001_initial.py
  smvsite/komitee/migrations/__init__.py
  smvsite/komitee/models.py
  smvsite/komitee/tests.py
  smvsite/komitee/urls.py
  smvsite/komitee/views.py
  smvsite/landing/admin.py
  smvsite/landing/migrations/0001_initial.py
  smvsite/landing/migrations/0002_delete_komitee.py
  smvsite/landing/models.py
  smvsite/smvsite/settings.py
  smvsite/smvsite/urls.py
Labels: enhancement

#22 Blog fix
  smvsite/blog/migrations/0003_auto_20200921_1803.py
  smvsite/blog/models.py
  smvsite/blog/tests.py
  smvsite/blog/urls.py
  smvsite/blog/views.py
Labels: bug

#24 Templates
  .gitignore
  .travis.yml
  smvsite/blog/templates/detail.html
  smvsite/blog/tests.py
  smvsite/blog/urls.py
  smvsite/blog/views.py
  smvsite/komitee/tests.py
  smvsite/landing/templates/index.html
  smvsite/landing/tests.py
  smvsite/landing/views.py
Labels: enhancement

#26 Docker
  .dockerignore
  .env/django.env
  .env/postgres.env
  .gitignore
  Dockerfile
  docker-compose.yml
  smvsite/docker-entrypoint.sh
  smvsite/smvsite/settings.py
  smvsite/smvsite/wsgi.py
Labels: enhancement

#27 Design
  .dockerignore
  .env/django.env
  smvsite/landing/templates/index.html
  smvsite/smvsite/settings.py
  smvsite/smvsite/wsgi.py
  smvsite/static/index/css/style.css
  smvsite/static/index/img/cropped-SMV-Theme.jpg
Labels: enhancement

#35 Templates
  smvsite/blog/migrations/0004_article_is_post.py
  smvsite/blog/models.py
  smvsite/blog/templates/detail.html
  smvsite/blog/tests.py
  smvsite/blog/views.py
  smvsite/komitee/admin.py
  smvsite/komitee/migrations/0002_delete_komitee.py
  smvsite/komitee/models.py
  smvsite/komitee/tests.py
  smvsite/komitee/views.py
  smvsite/landing/views.py
  smvsite/smvsite/settings.py
  smvsite/templates/detail.html
  smvsite/templates/header.html
  smvsite/templates/index.html
Labels: enhancement

#36 Markdown parser
  Pipfile
  Pipfile.lock
  requirements.txt
  smvsite/blog/tests.py
  smvsite/blog/views.py
  smvsite/komitee/tests.py
  smvsite/komitee/views.py
  smvsite/templates/detail.html
Labels: enhancement
